### ISSUE TITLE
Can the `dim` parameter for IFS datasets be removed?

### ISSUE THREAD

**Issue by d70-t** [digital-earths-global-hackathon/catalog#60]
@trackow 
The IFS datasets seem to have a `dim` parameter, which is not used by any of the other datasets. Is there any requirement to keep it? I'd otherwise suggest to (maybe virtually) merge the two parts. An easy option might be to just add the two paths to the catalog entry.

**Comment by trackow** [comment]
Our main IFS simulation that was rewritten and rechunked in Zarr for the global hackathon (**'ifs_tco3999-ng5_rcbmf_cf'** in the online catalog) includes both 2D and 3D without dim parameter.

For the existing parquets for the other two IFS datasets (**'ifs_tco3999-ng5_rcbmf'** and **'ifs_tco3999-ng5_deepoff'**) that are served online via the EERIE cloud I did not manage to add the two paths in one catalog entry for the EU catalog - I run into various issues when trying to combine them. For example, this last approach leads to a "GroupNotFoundError: group not found at path ''" after loading:

```yaml
  ifs_tco3999-ng5_rcbmf:
    args:
      consolidated: False
      urlpath: >
        {% with time_map = {'PT1H': 'hourly', 'P1M': 'monthly'}, zoom_map = {7: '128', 9: '512', 10: '1024', 11: '2048'} -%}
        - reference::/work/bm1344/DKRZ/kerchunks_batched/NGC-IFS-tco3999-ng5-production/2D_{{ time_map[time] }}_healpix{{ zoom_map[zoom] }}.parq
        - reference::/work/bm1344/DKRZ/kerchunks_batched/NGC-IFS-tco3999-ng5-production/3D_{{ time_map[time] }}_healpix{{ zoom_map[zoom] }}.parq
        {%- endwith %}
    driver: zarr
    parameters:
      time:
        allowed:
        - PT1H
        - P1M
        default: PT1H
        description: time resolution of the dataset
        type: str
      zoom:
        allowed:
        - 7
        - 11
        default: 7
        description: zoom level of the dataset
        type: int
    # metadata in online catalog
```

Alternatively, I could provide the 3D vars in an extra dataset if that is preferred, like how SCREAM CESS is split over several datasets [here](https://digital-earths-global-hackathon.github.io/catalog/), but I thought it's better to keep them together.
